---
title: "RNA-seq Demystified"
author: "UM Bioinformatics Core"
date: "`r Sys.Date()`"
output:
    ioslides_presentation:
        widescreen: true
        transition: 0.01
---

<!---
library(rmarkdown)
render('Module1_Introduction.Rmd')
--->

# Welcome!

## What is the Bioinformatics Core?

- The UM Bioinformatics Core helps researchers **design, analyze, and interpret** high-throughput genomics experiments.
- We have a number of analysts capable of helping design and analyze
    - gene expression,
    - variant calling,
    - chromatin accessibility and binding,
    - DNA methylation, and
    - single-cell experiments.
- We also provide letters of support for grants.

## Who are your instructors?

- Dana King
    - Journeyblurb

## Who are your instructors?

- Raymond Cavalcante
    - Journeyblurb

## What are the goals of this course?

- By the end of this course we hope that you will
    - feel confident in designing an RNA-seq experiment, and
    - understand the data analysis pipeline from raw reads to differentially expressed genes.
- Our purpose is not to be exhaustive, but to ease into a familiarity with concepts, data types, tools, and how they all connect to one another in the service of a biological question.
- In essence, we'd like to demystify what we, at the Bioinformatics Core, do.

# Housekeeping!

## Code of Conduct

- [DISCUSS] Insert SWC code of conduct or something modelled on it?

## Getting Help (Don't worry about it!)

- [DISCUSS] Raise your hand (screenshot?).
- A helper will contact you, and, if needed, you can go to a breakout room.

## Feedback with the yes/no flag

- Sometimes it will be helpful for us to get feedback during the lesson.
- [DISCUSS] Insert screenshot of yes/no flag.

## Etherpad

- [DISCUSS] Under what scenarios did we envision using this again?
    - Code updates?
    - ...?

## Mute or Chaos

- By default, we encourage audio muting to avoid unintended disturbances.
- **But just this once...**
    - Let's unmute and say Hello to everyone on the count of 1... 2... 3!

## Breaking Digital Ice

- We're all going to be transported into randomized breakout rooms to see what that's like.
- Introduce yourself. Tell the others what you hope to learn from the course.
