theme: jekyll-theme-slate
title: 'RNA-Seq Demystified Workshop'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Day 1
  - title: Welcome and Introductions
    url: Module1_Introductions
  - title: Schedule
    url: base/schedule
  - title: UNIX Shell Introduction
    url: Module2a_UNIXShell
  - title: Experimental Design, Library Prep, and Sequencing
    url: Module3a_Design_Prep_Seq
  - title: Data Quality Control
    url: Module3b_QC
  - title: Reference Genomes
    url: Module4a_Reference_Genomes
  - title: Sequence Alignment and Gene Quantification with STAR/RSEM
    url: Module6b_Alignment

  - heading: Day 2
  - title: Intro to R
    url: Module7a_IntroductionToR
  - title: DESeq2: Introduction
    url: Module8a_IntroductionToDESeq2
  - title: DESeq2: Initializing data objects
    url: Module8b_DESeq2Initialization
  - title: DESeq2: Differential Expression 
    url: Module8d_DESeq2DifferentialExpression
  - title: Visualizing data
    url: Module9a_SampleVisualizations
  - Coda and thanks
    url: tbd

